### ISSUE TITLE
Not working on Mac OS: /proc/cpuinfo does not exist

### ISSUE THREAD

**Issue by njh** [jchassin/homebridge-owfs#10]
Hi,

I have just tried running this on Mac OS but got had a problem because `/proc/cpuinfo` does not exist.

I found the attempted read here:
https://github.com/jchassin/homebridge-owfs/blob/master/index.js#L151

But it doesn't seem to do anything with `data`?
What is the purpose of reading /proc/cpuinfo?

Can this just be deleted?

Thanks,

nick.

**Comment by jchassin** [comment]
Hi Nick, to be honest, I don't remember why I've put this (maybe some debug code that I forgot to remove). I share your point of view that it is not used so you can remove it.
I've only tried this plugin on a raspberry, I am interrested by your feedback.
Another point is regarding a dependency to OWJS, I don't know if this works on mac, please tell us
Jean

PS : i will test to remove it in the coming days, if I have no issued, I'll update it here

**Comment by njh** [comment]
I deleted the lines and it enabled me to use your plugin running on my Mac.

So once it is gone, everything else works fine...  🎉 

But only tested `OWFS_Sensor` / `OWFS_DS18B20` so far.

**Comment by jchassin** [comment]
Fixed and published in 1.4.1
