### ISSUE TITLE
DS18B20 broken using plugin version higher than v1.4.4

### ISSUE THREAD

**Issue by wolfiesax** [jchassin/homebridge-owfs#14]
I've recently upgraded from v1.4.4 to latest v1.5.2 and realized DS18B20 is broken. I get the following error message with v1.5.0-1.5.2 during startup of Homebridge,
[9/24/2021, 10:25:12 PM] [Biblioteket] Initializing OWFS_Sensor accessory...
[9/24/2021, 10:25:12 PM] [Biblioteket] Configuring device : 28.75437C060000 on 192.168.1.89:4304
[9/24/2021, 10:25:12 PM] [Biblioteket] Capabilities: temperature
[9/24/2021, 10:25:12 PM] [Biblioteket] Unknwown device type

Running v1.4.4, which is working properly, gives me,
9/24/2021, 10:33:18 PM] [Biblioteket] Initializing OWFS_Sensor accessory...
[9/24/2021, 10:33:18 PM] [Biblioteket] Configuring device : 28.75437C060000 on 192.168.1.89:4304
[9/24/2021, 10:33:18 PM] [Biblioteket] Capabilities: temperature

I'm using the following configuration for DS18B20,
"accessories": [
  {
      "accessory": "OWFS_Sensor",
      "type": "OWFS_DS18B20",
      "name": "Biblioteket",
      "device": "28.75437C060000",
      "host_ip": "192.168.1.89",
      "host_port": "4304"
  }
  ]
together with node v14.17.6 and npm v6.14.15.

Could you please investigate this issue?

**Comment by jchassin** [comment]
My laptop is broken so difficult to investigate quickly but as default Sensor is 18B20 you can set in your config file :
"accessory": "OWFS_Sensor",
"type": "OWFS_Sensor",
this should fix the issue, this is the one I personally use
I'll check later why the way it is configured in your config file does not work, please give me feedback

**Comment by wolfiesax** [comment]
Hi. I can confirm your configuration works using v1.5.2. Thanks.

**Comment by jchassin** [comment]
Hi, I've just publish and tested a fix for your issue, so should be working with your initial configuration

**Comment by jchassin** [comment]
the version is 1.5.3

**Comment by jchassin** [comment]
no feedback from creator but seems fine
