### ISSUE TITLE
Any way off adding ESP8266 support to this plugin

### ISSUE THREAD

**Issue by tmur11** [jchassin/homebridge-owfs#16]
Trying to add DS18B20 sensors connected to ESP8266 but owfs doesn't appear to be support on those devices. None of the other homebridge options for DS18B20 support the history characteristic like yours does!

**Comment by jchassin** [comment]
Not sure whether this is possible, 
> First of all, at HW level you need to manage I2C or USB bus master interface
> Secondly I don't think there is a port of OWFS on ESP there should be information on https://owfs.org
Can't you put a Raspberrypi instead ?

**Comment by tmur11** [comment]
I'm not using I2C (only communicating with single sensor directly with IO pin using the w1_gpio module on the pi. Reason I ask is esp8266 form factor and power consumption. I'm using your plugin on main RPI connected to multiple remote Pi OFWS webservers. Just would like to add sensors from my nodemcu's (ESP8266)

**Comment by jchassin** [comment]
Hi I forgot I have your issue here, definitively your case won't be addressed here your architecture is too different. Hope you've find a way to do it.
