### ISSUE TITLE
Negative temperature values saturated to zero for DS18B20

### ISSUE THREAD

**Issue by wolfiesax** [jchassin/homebridge-owfs#4]
Hi. I can't get negative (Celsius) values to show when using OWFS_DS18B20, instead values seem to be saturated to 0.0.

I suspect this issue may be related to the (**minValue**) definition of Characteristic.CurrentTemperature in gen/HomeKitTypes.js of HAP-NodeJS:
```
Characteristic.CurrentTemperature = function() {
Characteristic.call(this, 'Current Temperature', '00000011-0000-1000-8000-0026BB765291');
this.setProps({
format: Characteristic.Formats.FLOAT,
unit: Characteristic.Units.CELSIUS,
maxValue: 100,
minValue: 0,
minStep: 0.1,
...
```
mentioned as an issue [here](https://github.com/KhaosT/HAP-NodeJS/issues/147).

Could anyone else reproduce the problem? If the problem is due to the HAP-NodeJS issue, how can I update HAP-NodeJS and or homebridge-owfs to fix this? The solution seems very simple by just changing the min value from 0 to -100 for instance.

//Ulf

**Comment by jchassin** [comment]
Hi, I've never tried negative values,  in principle, it is handled in lines 143 to 148.

I am going to perform a test and tell you

**Comment by jchassin** [comment]
Fixed in 1.3.3

**Comment by jchassin** [comment]
and tested in my freezer ;-)

**Comment by wolfiesax** [comment]
Verified ok here as well. Well done jchassin!!!

**Comment by tmur11** [comment]
@jchassin, @wolfiesax  I believe this is an issue again.
