### ISSUE TITLE
Plugin 'homebridge-owfs' tried to register with an incorrect plugin identifier: 'homebridge-owfs-devices'.

### ISSUE THREAD

**Issue by boernei** [jchassin/homebridge-owfs#8]
Hello
i always get this error when trying to use the plugin.

Plugin 'homebridge-owfs' tried to register with an incorrect plugin identifier: 'homebridge-owfs-devices'.

did i miss something?

**Comment by jchassin** [comment]
Hi, have you installed from npm or directly from github ?
I am the exact same error but does not affect the behavior of the plugin, i'll check as soon as I can
Jean

**Comment by boernei** [comment]
Thank you for the quick reply.

I reinstalled the plugin with the latest sourcecode. On npm there seems an old version.

This code in the master branch works. 
Thanks again

**Comment by jchassin** [comment]
Ok noted, I will publish it on NPM, the git version was under test on my side
Jean
