### ISSUE TITLE
when updateState  fails this.waiting_response[d_type] will never get false again

### ISSUE THREAD

**Issue by boernei** [jchassin/homebridge-owfs#9]
For my setup with 2 OWFS_DS18B20 Sensor, the updateState sometimes fails with the error in Line 290
this.log.error("Error reading " + this.ioPortName + '/' + d_type + ' ' + error);

When this functions exits with this error, this.waiting_response[d_type] = false;  will never be set. And there cannot be another measurement

   "accessories": [
        {
            "accessory": "OWFS_Sensor",
            "type": "OWFS_DS18B20",
            "name": "Temperature Sensor 1",
            "device": "28.59E02C222001"
        },
        {
            "accessory": "OWFS_Sensor",
            "type": "OWFS_DS18B20",
            "name": "Temperature Sensor 2",
            "device": "28.63C851222001"
        }
    ],

**Comment by jchassin** [comment]
Fixed, thanks for your feedback

**Comment by boernei** [comment]
thanks
